version: "3.9"

services:

  wpcli:
    command: tail -f /dev/null
    container_name: maap-portal-wpcli
    depends_on:
      - www
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME_FILE=/run/secrets/WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER_FILE=/run/secrets/WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/WORDPRESS_DB_PASSWORD
    image: wordpress:cli-php7.4
    secrets:
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    user: 1000:1000
    volumes:
      - ./www/data:/var/www/html

  www:
    container_name: 'maap-portal-www'
    build:
      dockerfile: Dockerfile
      context: ./www
    depends_on:
      db:
        condition: service_healthy
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME_FILE=/run/secrets/WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER_FILE=/run/secrets/WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/WORDPRESS_DB_PASSWORD
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
    image: 'maap-portal-www'
    ports:
      - '8080:80'
    restart: always
    secrets:
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    user: 1000:1000
    volumes:
      - "./www/data:/var/www/html"

  db:
    container_name: 'maap-portal-db'
    build:
      dockerfile: Dockerfile
      context: ./db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE_FILE=/run/secrets/MYSQL_DATABASE
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
    healthcheck:
        test: "exit 0"
    image: 'maap-portal-db'
    ports:
      - '3306:3306'
    restart: always
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - "./db/init/:/docker-entrypoint-initdb.d/"
      - "./db/data:/var/lib/mysql"

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./db/secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_DATABASE:
    file: ./db/secrets/MYSQL_DATABASE.txt
  MYSQL_USER:
    file: ./db/secrets/MYSQL_USER.txt
  MYSQL_PASSWORD:
    file: ./db/secrets/MYSQL_PASSWORD.txt
  WORDPRESS_DB_NAME:
    file: ./www/secrets/WORDPRESS_DB_NAME.txt
  WORDPRESS_DB_USER:
    file: ./www/secrets/WORDPRESS_DB_USER.txt
  WORDPRESS_DB_PASSWORD:
    file: ./www/secrets/WORDPRESS_DB_PASSWORD.txt