version: "3.9"

services:

  db:
    container_name: 'maap-portal-db'
    build:
      dockerfile: Dockerfile
      context: ./db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE_FILE=/run/secrets/MYSQL_DATABASE
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
    healthcheck:
        test: "exit 0"
    image: 'maap-portal-db'
    ports:
      - '3306:3306'
    restart: always
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./db/data:/var/lib/mysql"

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./db/secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_DATABASE:
    file: ./db/secrets/MYSQL_DATABASE.txt
  MYSQL_USER:
    file: ./db/secrets/MYSQL_USER.txt
  MYSQL_PASSWORD:
    file: ./db/secrets/MYSQL_PASSWORD.txt